# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

City.create([
  { :name => "Hyderabad", :country_id => 1, :created_at => "2012-12-06 15:58:23", :updated_at => "2012-12-06 15:58:26" },
  { :name => "pune", :country_id => 1, :created_at => "2012-12-06 15:58:38", :updated_at => "2012-12-06 15:58:40" },
  { :name => "london", :country_id => 2, :created_at => "2012-12-07 00:00:00", :updated_at => "2012-12-07 15:32:08" },
  { :name => "Benguluru", :country_id => 1, :created_at => "2012-12-07 10:44:13", :updated_at => "2012-12-07 10:44:13" },
  { :name => "Mumbai", :country_id => 1, :created_at => "2012-12-07 10:44:13", :updated_at => "2012-12-07 10:44:13" },
  { :name => "Kolkata", :country_id => 1, :created_at => "2012-12-07 10:44:13", :updated_at => "2012-12-07 10:44:13" },
  { :name => "Dhakha", :country_id => 3, :created_at => "2012-12-07 11:46:06", :updated_at => "2012-12-07 11:46:06" },
  { :name => "Sydney", :country_id => 4, :created_at => "2012-12-07 11:51:01", :updated_at => "2012-12-07 11:51:01" },
  { :name => "Melborne", :country_id => 4, :created_at => "2012-12-07 11:51:01", :updated_at => "2012-12-07 11:51:01" },
  { :name => "bhuvaneswar", :country_id => 1, :created_at => "2012-12-11 13:31:43", :updated_at => "2012-12-11 13:31:43" }
], :without_protection => true )



Clinic.create([
  { :cliniccode => 216, :name => "SVC", :displayname => "SVC", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "SVC", :address2 => "SVC", :location_id => 1, :landmarks => "near startue", :city => "hyderabad", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 216, :name => "SVCs", :displayname => "SVCs", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "SVC", :address2 => "SVC", :location_id => 1, :landmarks => "near startue", :city => "golconda", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 216, :name => "Vijay", :displayname => "Vijay", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Vijay", :address2 => "Vijay", :location_id => 2, :landmarks => "near startue", :city => "Sanath Nagar", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 243, :name => "Vidya", :displayname => "Vidya", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Vidya", :address2 => "Vidya", :location_id => 3, :landmarks => "near startue", :city => "Sanath Nagar", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 243, :name => "Hari", :displayname => "Hari", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Hari", :address2 => "Hari", :location_id => 4, :landmarks => "near startue", :city => "Borabanda", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 243, :name => "Shanmuk", :displayname => "Shanmuk", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Shanmuk", :address2 => "Shanmuk", :location_id => 5, :landmarks => "near startue", :city => "Erragadda", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 243, :name => "Appi", :displayname => "Appi", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Appi", :address2 => "Appi", :location_id => 4, :landmarks => "near startue", :city => "SR Nagar", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 243, :name => "Sravan", :displayname => "Sravan", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Sravan8", :address2 => "Sravan", :location_id => 3, :landmarks => "near startue", :city => "SR Nagar", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 243, :name => "Teja", :displayname => "Teja", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Teja", :address2 => "Teja", :location_id => 3, :landmarks => "near startue", :city => "SR Nagar", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 243, :name => "Balaji", :displayname => "Balaji", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Balaji", :address2 => "Balaji", :location_id => 2, :landmarks => "near startue", :city => "SR Nagar", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 243, :name => "Venkatesh", :displayname => "Venkatesh", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Venkatesh", :address2 => "Venkatesh", :location_id => 2, :landmarks => "near startue", :city => "SR Nagar", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil },
  { :cliniccode => 243, :name => "Nagendar", :displayname => "Nagendar", :branches => 1, :discontinue => false, :expdate => "2012-12-31", :address1 => "Nagendar", :address2 => "Nagendar", :location_id => 4, :landmarks => "near startue", :city => "SR Nagar", :state => "india", :country => nil, :pin => nil, :fax => nil, :website => nil, :email => nil, :altemail => nil, :choosefile => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )


